### ISSUE TITLE
Calendar icon don't open the calendar application

### ISSUE THREAD

**Issue by c0pie** [adolfintel/Clock31#2]
Recently i got the following error message after i'm touching the calendar icon on the desktop widget:
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022111000:user/release-keys
package: com.android.calendar:33
process: com.android.calendar

java.lang.NullPointerException: cEvents.getString(PROJECTION_RRULE_INDEX) must not be null
	at com.android.calendar.Event$Companion.generateEventFromCursor(Event.kt:327)
	at com.android.calendar.Event$Companion.buildEventsFromCursor(Event.kt:287)
	at com.android.calendar.Event$Companion.loadEvents(Event.kt:187)
	at com.android.calendar.EventLoader$LoadEventsRequest.processRequest(EventLoader.kt:126)
	at com.android.calendar.EventLoader$LoaderThread.run(EventLoader.kt:186)

```
The same behaviour with the Version 1.0.1.
But at the moment, no system update in the meantime, 'it works' without the error message. Strange.
Now a click on the icon does not open the installed calendar application [(simple- calendar](https://github.com/SimpleMobileTools/Simple-Calendar)) but only a system own application (sorry, i am new on GrapheneOS; there is no such thing like a genuine calendar application)

My system:
Google Pixel 6a
Android 13
GrapheneOS

**Comment by adolfintel** [comment]
That looks like a crash inside the android calendar app (not simple calendar or clock31). Does it work if you just launch it from the menu?

**Comment by c0pie** [comment]
Sorry, i don't know exactly what you mean. The menu from what? The genuine calendar application?
I have to apologize, there is a calendar application, but it is marked as 'system app', not directly accessible via menu or so.
Yesterday there was an update from GrapheneOS. After this, if i touch now the calendar icon on the widget i see shortly the start screen from the (system app) calendar application (not simple calendar), but it closes immediately. After the second or third time a message from android appears: "calendar is terminated repeatedly" and if i touch "show details" i get the same error message like in the first post.
Maybe a problem with the calendar implementation from Graphene?

**Comment by c0pie** [comment]
The "App-Info" said:
com.android.calendar
versionCode 33
targetSdk 30
minSdk 33

Package name: come.android.calendar

It sounds like it's the 'original', whatever that means, (very old) calendar app from google itself. 
Do you mean the app menu from the launcher? Yes, there is no icon there.
If i deactivate the app and touch the icon on your widget nothing happens. My actual calendar app still works.

I can install your widget on an older device (with LineageOS) in the next few days and see if it works there.

**Comment by adolfintel** [comment]
So yeah, it's a placeholder app, that explains why it can't handle the request properly.

I developed the app on LineageOS and it has a com.lineageos.etar app, which is their custom calendar, and the widget doesn't crash even if the calendar app is disabled.

Note that Clock31 doesn't try to open a specific app, it just launches the system default, so there might be an option in your calendar or in the system settings to choose the default calendar app.

**Comment by c0pie** [comment]
So, i tested the widget on an older smartphone (LineageOS 16, root (Android 9)). If i touch the calendar icon on the widget nothing happens. No error message, but the calendar doesn't open.

Do you plan to expand the app? I've been using an (very) old version of cLock for many years across different smartphones and android versions. The old version still works, but there a few problems.

**Comment by adolfintel** [comment]
I don't understand this calendar icon problem, it's been reported multiple times but in my testing it works even on my oldest phone with Android 5...

That's what I was doing too, I kept a cLock apk from Lineage 16 because that widget was just perfect for me.

This widget already suits my needs as it is but I do plan to add some settings at some point, like being able to hide the color bars, choosing how to display the dates, etc., the same stuff that was present in the old cLock. I'm definitely not adding the weather thing though, I never liked it.

Feel free to send some PRs if you want.
